// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBld_0ewJ4urjCzG49p4c__TDizdWX2pjI',
    appId: '1:622326394017:web:451b7062b9a9b18bca14e0',
    messagingSenderId: '622326394017',
    projectId: 'flutter1-d468a',
    authDomain: 'flutter1-d468a.firebaseapp.com',
    storageBucket: 'flutter1-d468a.firebasestorage.app',
    measurementId: 'G-RFDKRY0TPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_XHcVbsTWSoiIIKz4FGvVbADhw-KWA-U',
    appId: '1:622326394017:android:89962aa47c5bbfd4ca14e0',
    messagingSenderId: '622326394017',
    projectId: 'flutter1-d468a',
    storageBucket: 'flutter1-d468a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KDmCjssmt7aUC0IEIL9ytswC17X_qD8',
    appId: '1:622326394017:ios:b450a9478908affcca14e0',
    messagingSenderId: '622326394017',
    projectId: 'flutter1-d468a',
    storageBucket: 'flutter1-d468a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KDmCjssmt7aUC0IEIL9ytswC17X_qD8',
    appId: '1:622326394017:ios:b450a9478908affcca14e0',
    messagingSenderId: '622326394017',
    projectId: 'flutter1-d468a',
    storageBucket: 'flutter1-d468a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBld_0ewJ4urjCzG49p4c__TDizdWX2pjI',
    appId: '1:622326394017:web:18488457ddb34cd2ca14e0',
    messagingSenderId: '622326394017',
    projectId: 'flutter1-d468a',
    authDomain: 'flutter1-d468a.firebaseapp.com',
    storageBucket: 'flutter1-d468a.firebasestorage.app',
    measurementId: 'G-Z858KVW51B',
  );
}
